### ISSUE TITLE
指向自己的数据库服务器IP和数据库账号密码，但是数据库连接失败

### ISSUE THREAD

**Issue by bitlin** [aaronchen2k/ngtesting-platform#41]
通过运行jar的方式在mac本地运行。
在运行之前修改了 /ngtesting-platform/src/main/resources/application.yml 中数据库host IP和登录账号密码，并且运行jar时指定了数据库IP，但是运行结果仍失败。从日志来看，所修改的数据库信息并没有生效。

安装文档方便具体说明一下需要改哪些地方么？

2018-08-24 09:49:18,244:INFO main (DruidDataSourceAutoConfigure.java:56) - Init DruidDataSource
Fri Aug 24 09:49:19 CST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-08-24 09:49:20,566:ERROR main (DruidDataSource.java:870) - init datasource error, url: jdbc:mysql://47.94.237.36:3306/ngtesting-web?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
java.sql.SQLException: Access denied for user 'ngtesting'@'183.157.87.85' (using password: YES) 
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.Conn

**Comment by aaronchen2k** [comment]
user 'ngtesting'@'183.157.87.85' (using password: YES)
以上日志，说明数据库连接字符串已经修改成功了

**Comment by bitlin** [comment]
我已经改成自己的IP和数据库名及密码了，日志里 user 'ngtesting'@'183.157.87.85' (using password: YES) 不是我的账号。 相同的数据库账号密码连了我的远程数据库，确定没问题的

**Comment by bitlin** [comment]
我已经改成自己的IP和数据库名及密码了，日志里 user 'ngtesting'@'183.157.87.85' (using password: YES) 不是我的账号。 相同的数据库账号密码连了我的远程数据库，确定没问题的。
命令行先不指定参数，修改application.yml里的config.mysql.host，host是localhost。 应该是application.yml的修改没生效吧

Caused by: java.sql.SQLException: Access denied for user 'ngtesting'@'localhost' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]

**Comment by aaronchen2k** [comment]
application.yml默认用的是prod的profile，你去掉命令行参数 HOST 183.157.87.85 是哪来的？

**Comment by bitlin** [comment]
https://github.com/aaronchen2k/ngtesting-platform/issues/41#issuecomment-415643067 

我也是很好奇这个IP哪里来的  新clone下来的代码，除了application.yml 其他代码都没动过

**Comment by aaronchen2k** [comment]
只有修改了xml，或命令行提供了参数，配置的MySQL主机地址才会变化，请确认
